
/**
 * LICENSE:
 *
 * MIT License
 *
 * Copyright (c) 2026 Henrik A. Glass
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 * MIT License
 *
 *
 * ABOUT:
 *
 * hgl_earchop.h implements an earclipping algorithm for basic polygon triangulation.
 *
 *
 * USAGE:
 *
 * See hgl_earchop() description for more details.
 *
 *
 * EXAMPLE:
 *
 *     #define HGL_EARCHOP_IMPLEMENTATION
 *     #include "hgl_earchop.h"
 *
 *     typedef struct 
 *     {
 *         float x, y;
 *     } MyVec2;
 *
 *     typedef struct 
 *     {
 *         MyVec2 pos;
 *         uint32_t color_rgba8;
 *     } MyVertex;
 *
 *                      .
 *                      .
 *                      .
 *
 *     // polygon boundary defined in CW winding order
 *     MyVertex verts[] = {
 *         (MyVertex){ .pos = {-2.0f,  4.0f}, .color_rgba8 = 0xFF0000FFu},
 *         (MyVertex){ .pos = {-1.0f,  1.0f}, .color_rgba8 = 0xFF0000FFu},
 *         (MyVertex){ .pos = { 1.0f,  3.0f}, .color_rgba8 = 0xFF0000FFu},
 *         (MyVertex){ .pos = { 1.0f,  6.0f}, .color_rgba8 = 0x00FF00FFu},
 *         (MyVertex){ .pos = { 4.0f, -1.0f}, .color_rgba8 = 0x00FF00FFu},
 *         (MyVertex){ .pos = { 1.0f, -2.0f}, .color_rgba8 = 0x00FF00FFu},
 *         (MyVertex){ .pos = { 2.0f, -1.0f}, .color_rgba8 = 0xFFFFFFFFu},
 *         (MyVertex){ .pos = {-2.0f, -2.0f}, .color_rgba8 = 0x000000FFu},
 *     };
 *                      
 *     int n_verts = (int)(sizeof(verts) / sizeof(verts[0]));
 *     int index_buffer_length = hgl_earchop_resulting_index_buffer_length(n_verts);
 *     int *indices = malloc(sizeof(int) * index_buffer_length);
 *
 *     hgl_earchop(verts,                         // pointer to vertices
 *                 n_verts,                       // # of vertices
 *                 (int)sizeof(MyVertex),         // vertex stride
 *                 (int)offsetof(MyVertex, pos),  // offset of xy position information in vertex
 *                 indices,                       // pointer to buffer in which to store indices (can be NULL iff HGL_EARCHOP_ALLOC is defined)
 *                 HGL_EARCHOP_CW,                // Polygon boundary winding order
 *                 HGL_EARCHOP_CCW);              // Winding order of resulting triangles in indices
 *     
 *     draw_mesh(verts, indices);  // or whatever
 *
 *
 * AUTHOR: Henrik A. Glass
 *
 */

#ifndef HGL_EARCHOP_H
#define HGL_EARCHOP_H

/*--- Include files ---------------------------------------------------------------------*/

/*--- Public macros ---------------------------------------------------------------------*/

#ifndef HGL_EARCHOP_MAX_POLYGON_VERTICES
#  define HGL_EARCHOP_MAX_POLYGON_VERTICES          (1 << 16)
#endif

/*--- Public type definitions -----------------------------------------------------------*/

typedef enum {
    HGL_EARCHOP_CW,
    HGL_EARCHOP_CCW,
} HglEarchopWindingOrder;

/*--- Public variables ------------------------------------------------------------------*/

/*--- Public function prototypes --------------------------------------------------------*/

/* 
 * Returns the maximum number of triangles that can be generated by triangulating a 
 * polygon with `n_verts` # of vertices. If HGL_EARCHOP_KEEP_DEGENERATE_TRIANGLES is
 * defined, then this number will be an exact fit.
 */
int hgl_earchop_n_triangles(int n_verts);

/**
 * Triangulates `verts` and stores the resulting triangle indices into `indices`.
 *
 * @param verts                     Pointer to beginning of vertex data.
 * @param n_verts                   Total number of vertices in `verts`.
 * @param vert_stride               The distance, in bytes, between two consecutive vertices in `verts`.
 * @param vert_xy_offset            The offset, in bytes, from the start of a vertex to its xy position data.
 * @param triangle_indices          Pointer to buffer in which to store triangle indices. May be NULL iff HGL_EARCHOP_ALLOC is defined.
 * @param n_triangle_indices        Pointer to integer in which to store the number of generated triangle indices.
 * @param polygon_winding_order     The winding order of the vertices in `verts`.
 * @param triangle_winding_order    The winding order of the resulting triangles in `indices`.
 *
 * @return  0 on success, -1 on error.
 */
int hgl_earchop(void *verts,
                int n_verts,
                int vert_stride,
                int vert_xy_offset,
                int *triangle_indices,
                int *n_triangle_indices,
                HglEarchopWindingOrder polygon_winding_order,
                HglEarchopWindingOrder triangle_winding_order);

#endif /* HGL_EARCHOP_H */

#ifdef HGL_EARCHOP_IMPLEMENTATION

/*--- Include files ---------------------------------------------------------------------*/

#include <stdio.h>
#include <assert.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/*--- Private macros --------------------------------------------------------------------*/

#if !defined(HGL_EARCHOP_ALLOC) && \
    !defined(HGL_EARCHOP_FREE)
#  include <stdlib.h>
#  define HGL_EARCHOP_ALLOC(s) NULL
#  define HGL_EARCHOP_FREE(s) (void)s 
#endif

/*--- Private type definitions ----------------------------------------------------------*/

typedef struct
{
    float x;
    float y;
} HglEarchopVec2;

typedef struct
{
    int *const buf;
    int size;
    int gap_start;
    int gap_end;
    int cursor;
} HglEarchopGapBuffer;

/*--- Private function prototypes -------------------------------------------------------*/

/* vec2 */
static inline HglEarchopVec2 hgl_earchop_vec2_get_(void *verts, int vert_stride, int vert_xy_offset, int index);
static inline HglEarchopVec2 hgl_earchop_vec2_sub_(HglEarchopVec2 a, HglEarchopVec2 b);
static inline float hgl_earchop_vec2_wedge_(HglEarchopVec2 a, HglEarchopVec2 b);
static inline float hgl_earchop_vec2_det_(HglEarchopVec2 a,
                                          HglEarchopVec2 b,
                                          HglEarchopVec2 c);
static inline bool hgl_earchop_vec2_point_in_triangle_(HglEarchopVec2 p,
                                                       HglEarchopVec2 a,
                                                       HglEarchopVec2 b,
                                                       HglEarchopVec2 c,
                                                       HglEarchopWindingOrder winding_order);
/* gap buffer */
static inline HglEarchopGapBuffer hgl_earchop_gb_make_(int *const buf, int size);
static inline int hgl_earchop_gb_length_(HglEarchopGapBuffer *gbuf);
static inline int hgl_earchop_gb_at_cursor_(HglEarchopGapBuffer *gbuf, int step);
static inline void hgl_earchop_gb_delete_at_cursor_(HglEarchopGapBuffer *gbuf);
static inline void hgl_earchop_gb_fill_range_(HglEarchopGapBuffer *gbuf, int first, int last);
static inline void hgl_earchop_gb_step_cursor_(HglEarchopGapBuffer *gbuf, int step);
static inline void hgl_earchop_gb_split_on_cursor_(HglEarchopGapBuffer *gbuf);

#if 0
static inline void gb_debug_print(HglEarchopGapBuffer *gbuf);
#endif

/*--- Public variables ------------------------------------------------------------------*/

/*--- Private variables -----------------------------------------------------------------*/

/*--- Public functions ------------------------------------------------------------------*/

int hgl_earchop_n_triangles(int n_verts)
{
    return (n_verts - 2); 
}

int hgl_earchop(void *verts,
                int n_verts,
                int vert_stride,
                int vert_xy_offset,
                int *triangle_indices,
                int *n_triangle_indices,
                HglEarchopWindingOrder polygon_winding_order,
                HglEarchopWindingOrder triangle_winding_order)
{
    bool internal_alloc = false;
    if (triangle_indices == NULL) {
        triangle_indices = HGL_EARCHOP_ALLOC(hgl_earchop_resulting_index_buffer_length(n_verts) * 
                                                 sizeof(triangle_indices[0]));
        internal_alloc = true;
        if (triangle_indices == NULL) {
            fprintf(stderr, "[hgl_earchop.h] Error: Failed to allocate space for `triangle_indices` which was "
                            "passed to `hgl_earchop()` with a value of `NULL`. Note: hgl_earchop.h defines no "
                            "default allocator function for HGL_EARCHOP_ALLOC. If you wish for hgl_earchop.h "
                            "to allocate memory for you then you must explicitly define it before including "
                            "`hgl_earchop.h`; e.g. `#define HGL_EARCHOP_ALLOC malloc`\n");
            return -1;
        }
    }

    static int gbuf_buf[HGL_EARCHOP_MAX_POLYGON_VERTICES];
    HglEarchopGapBuffer gbuf = hgl_earchop_gb_make_(gbuf_buf, n_verts);
    hgl_earchop_gb_fill_range_(&gbuf, 0, n_verts - 1);

    
    int tri_idx = 0;
    int i0, i1, i2;
    HglEarchopVec2 v0, v1, v2, v10, v12;
    HglEarchopVec2 p;
    int n_iterations_since_last_valid_ear = 0;
    gbuf.cursor = hgl_earchop_gb_length_(&gbuf) - 1;
    while (hgl_earchop_gb_length_(&gbuf) > 3) {

        if (n_iterations_since_last_valid_ear > hgl_earchop_gb_length_(&gbuf)) {
            fprintf(stderr, "[hgl_earchop.h] Error: Failed to create a valid triangulation of vertices at %p.\n", verts);
            goto out_err;
        }

        /* step to next vertex */
        hgl_earchop_gb_step_cursor_(&gbuf, 1);
        i0 = hgl_earchop_gb_at_cursor_(&gbuf, -1);
        i1 = hgl_earchop_gb_at_cursor_(&gbuf,  0);
        i2 = hgl_earchop_gb_at_cursor_(&gbuf,  1);
        v0 = hgl_earchop_vec2_get_(verts, vert_stride, vert_xy_offset, i0);
        v1 = hgl_earchop_vec2_get_(verts, vert_stride, vert_xy_offset, i1);
        v2 = hgl_earchop_vec2_get_(verts, vert_stride, vert_xy_offset, i2);
        v10 = hgl_earchop_vec2_sub_(v0, v1);
        v12 = hgl_earchop_vec2_sub_(v2, v1);
        
        /* angle convex w.r.t. chosen winding order? */
        float wedge = hgl_earchop_vec2_wedge_(v10, v12);
        bool is_convex_angle = ((polygon_winding_order == HGL_EARCHOP_CW)  && (wedge >= 0.0f)) ||
                               ((polygon_winding_order == HGL_EARCHOP_CCW) && (wedge <= 0.0f));
        if (!is_convex_angle) {
            n_iterations_since_last_valid_ear++;
            continue;
        }

        /* No other vertices in ear candidate? */
        bool point_inside = false;
        int tmp_cursor = gbuf.cursor;
        hgl_earchop_gb_step_cursor_(&gbuf, 2);
        while (true) {
            int idx = hgl_earchop_gb_at_cursor_(&gbuf, 0);

            /* reached first vertex of ear? exit */
            if (idx == i2) {
                break;
            }

            /* vertex position is inside ear candidate? fail and exit loop */
            p = hgl_earchop_vec2_get_(verts, vert_stride, vert_xy_offset, idx);
            if (hgl_earchop_vec2_point_in_triangle_(p, v0, v1, v2, polygon_winding_order)) {
                point_inside = true;
                break;
            }

            /* good so far - step to next vertex */
            hgl_earchop_gb_step_cursor_(&gbuf, 1);
        }
        gbuf.cursor = tmp_cursor;
        if (point_inside) {
            n_iterations_since_last_valid_ear++;
            continue;
        }

        /* all tests passed so far - this is a valid ear - delete vertex */
        n_iterations_since_last_valid_ear = 0;
        hgl_earchop_gb_delete_at_cursor_(&gbuf);

#ifndef HGL_EARCHOP_KEEP_DEGENERATE_TRIANGLES
        /* Triangle has a zero area? discard from output. */
        float tri_area = hgl_earchop_vec2_det_(v0, v1, v2);
        if (tri_area == 0.0f) {
            continue;
        }
#endif

        /* Add triangle */
        if (triangle_winding_order != polygon_winding_order) {
            triangle_indices[tri_idx]     = i2; 
            triangle_indices[tri_idx + 1] = i1; 
            triangle_indices[tri_idx + 2] = i0; 
        } else {
            triangle_indices[tri_idx]     = i0; 
            triangle_indices[tri_idx + 1] = i1; 
            triangle_indices[tri_idx + 2] = i2; 
        }
        tri_idx += 3;
    }

    i0 = hgl_earchop_gb_at_cursor_(&gbuf, -1);
    i1 = hgl_earchop_gb_at_cursor_(&gbuf,  0);
    i2 = hgl_earchop_gb_at_cursor_(&gbuf,  1);

#ifndef HGL_EARCHOP_KEEP_DEGENERATE_TRIANGLES
    /* Remaining triangle has a zero area? discard from output and skip directly to return. */
    float tri_area = hgl_earchop_vec2_det_(hgl_earchop_vec2_get_(verts, vert_stride, vert_xy_offset, i0),
                                           hgl_earchop_vec2_get_(verts, vert_stride, vert_xy_offset, i1),
                                           hgl_earchop_vec2_get_(verts, vert_stride, vert_xy_offset, i2));
    if (tri_area == 0.0f) {
        *n_triangle_indices = tri_idx;
        return 0;
    }
#endif

    /* only 3 vertices remaining, making a triangle, insert it too */
    if (triangle_winding_order != polygon_winding_order) {
        triangle_indices[tri_idx]     = i2;
        triangle_indices[tri_idx + 1] = i1;
        triangle_indices[tri_idx + 2] = i0;
    } else {
        triangle_indices[tri_idx]     = i0;
        triangle_indices[tri_idx + 1] = i1;
        triangle_indices[tri_idx + 2] = i2;
    }
    tri_idx += 3;

    *n_triangle_indices = tri_idx;
    return 0;

out_err:
    if (internal_alloc && (triangle_indices != NULL)) {
        HGL_EARCHOP_FREE(triangle_indices);
    }
    return -1;

}

/*--- Private functions -----------------------------------------------------------------*/

/* ================= vec2 =============== */

static inline HglEarchopVec2 hgl_earchop_vec2_get_(void *verts, int vert_stride, int vert_xy_offset, int index)
{
    union {
        uint8_t *p_u8;
        HglEarchopVec2 *p_v2;
    } u;
    u.p_u8 = (uint8_t *)verts + index*vert_stride + vert_xy_offset;
    return *u.p_v2;
}

static inline HglEarchopVec2 hgl_earchop_vec2_sub_(HglEarchopVec2 a, HglEarchopVec2 b)
{
    return (HglEarchopVec2) {
        .x = a.x - b.x,
        .y = a.y - b.y,
    };
}

static inline float hgl_earchop_vec2_wedge_(HglEarchopVec2 a, HglEarchopVec2 b)
{
    return a.x * b.y - a.y * b.x;
}

static inline float hgl_earchop_vec2_det_(HglEarchopVec2 a,
                                          HglEarchopVec2 b,
                                          HglEarchopVec2 c)
{
    return (b.y - a.y) * (c.x - a.x) - (b.x - a.x) * (c.y - a.y);
}

static inline bool hgl_earchop_vec2_point_in_triangle_(HglEarchopVec2 p,
                                                       HglEarchopVec2 a,
                                                       HglEarchopVec2 b,
                                                       HglEarchopVec2 c,
                                                       HglEarchopWindingOrder winding_order)
{
    float w0 = hgl_earchop_vec2_det_(p, b, c);
    float w1 = hgl_earchop_vec2_det_(a, p, c);
    float w2 = hgl_earchop_vec2_det_(a, b, p);
    if (winding_order == HGL_EARCHOP_CW) {
        return w0 > 0.0f && w1 > 0.0f && w2 > 0.0f;
    } else {
        return w0 < 0.0f && w1 < 0.0f && w2 < 0.0f;
    }
}

/* ============== gap buffer ============ */

static HglEarchopGapBuffer hgl_earchop_gb_make_(int *const buf, int size)
{
    assert(size <= HGL_EARCHOP_MAX_POLYGON_VERTICES);
    return (HglEarchopGapBuffer) {
        .buf       = buf,
        .size      = size,
        .gap_start = 0,
        .gap_end   = size,
        .cursor    = 0,
    };
}

static int hgl_earchop_gb_length_(HglEarchopGapBuffer *gbuf)
{
    return gbuf->size - (gbuf->gap_end - gbuf->gap_start);
}

static int hgl_earchop_gb_at_cursor_(HglEarchopGapBuffer *gbuf, int step)
{
    int res;
    hgl_earchop_gb_step_cursor_(gbuf, step);
    int s = gbuf->gap_start;
    int e = gbuf->gap_end;
    int c = gbuf->cursor;
    if (c < s) {
        res = gbuf->buf[c];
    } else {
        res = gbuf->buf[c + (e - s)];
    }
    hgl_earchop_gb_step_cursor_(gbuf, -step);
    return res;
}

static void hgl_earchop_gb_delete_at_cursor_(HglEarchopGapBuffer *gbuf)
{
    assert(hgl_earchop_gb_length_(gbuf) > 0);
    hgl_earchop_gb_split_on_cursor_(gbuf);
    //gbuf->cursor--;
    gbuf->gap_end++;
}

static void hgl_earchop_gb_fill_range_(HglEarchopGapBuffer *gbuf, int first, int last)
{
    assert(last >= first);
    int gblen = hgl_earchop_gb_length_(gbuf);
    int n = (last - first) + 1;
    assert((gblen + n) <= gbuf->size);
    hgl_earchop_gb_split_on_cursor_(gbuf);
    for (int i = first; i <= last; i++) {
        gbuf->buf[gbuf->cursor] = i;
        gbuf->cursor++;
    }
    gbuf->gap_start += n;
    gbuf->cursor = 0;
}

static void hgl_earchop_gb_step_cursor_(HglEarchopGapBuffer *gbuf, int step)
{
    /* real modulo */
    int length = hgl_earchop_gb_length_(gbuf);
    gbuf->cursor += step;
    gbuf->cursor %= length;
    gbuf->cursor += (gbuf->cursor < 0) ? length : 0;
}

static void hgl_earchop_gb_split_on_cursor_(HglEarchopGapBuffer *gbuf)
{
    int s = gbuf->gap_start;
    int e = gbuf->gap_end;
    int d = gbuf->cursor - s; 
    if (d < 0) { // L
        memcpy(&gbuf->buf[e] + d, &gbuf->buf[gbuf->cursor], -(d*sizeof(gbuf->buf[0])));
    } else if (d > 0) { // R
        memcpy(&gbuf->buf[s], &gbuf->buf[e], d*sizeof(gbuf->buf[0]));
    }
    gbuf->gap_start = gbuf->cursor;
    gbuf->gap_end = e + d;
}

#if 0
static void gb_debug_print(HglEarchopGapBuffer *gbuf)
{
    int c = gbuf->cursor;
    int s = gbuf->gap_start;
    int e = gbuf->gap_end;
    int l = e - s;
    printf("[");
    for (int i = 0; i < gbuf->size; i++) {
        if (c <= s) {
            if (i == c) printf("|");
        } else {
            if (i == c + l) printf("|");
        }
        if (i < s || i >= e) printf("%d,", gbuf->buf[i]);
        else printf("_,");
    }
    printf("]  --->   \"");
    for (int i = 0; i < gbuf->size; i++) {
        if (c <= s) {
            if (i == c) printf("|");
        } else {
            if (i == c + l) printf("|");
        }
        if (i < s || i >= e) printf("%d", gbuf->buf[i]);
    }
    printf("\"\n");
    printf("c = %d, s = %d, e = %d\n", gbuf->cursor, gbuf->gap_start, gbuf->gap_end);
}
#endif

#endif /* HGL_EARCHOP_IMPLEMENTATION */

// TODO Optional edge-flip mesh refining
